apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-candidate
  annotations:
    tekton.dev/displayName: "Cleans up candidate version in the git repo"
spec:
  description: >-
    This task cleans up the candidate version in the git repo

  resources:
    inputs:
    - name: source
      type: git
      description: Holds git repo

  steps:
  - name: cleanup-candidate
    workingDir: $(resources.inputs.source.path)
    image: alpine/git:latest
    script: |
      #!/usr/bin/env sh
      echo "Cleanup candidate version"
