apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: promote-candidate
  annotations:
    tekton.dev/displayName: "Promote candidate version in the git repo"
spec:
  description: >-
    This task promotes the candidate version in the git repo

  params:
    - name: VERSION
      description: version of the candidate deployment
    - name: USER
      description: Github username
    - name: REPO
      description: Github repo name
    - name: BRANCH
      description: Base branch PR is opened against
    - name: GITHUB-TOKEN-SECRET
      description: Holds Github token

  steps:
  - name: promote-candidate
    image: alpine/git:latest
    script: |
      #!/usr/bin/env sh
      echo "Promote candidate version"

      git config --global user.email 'iter8@iter8.tools'
      git config --global user.name 'Iter8'
      git clone https://$(params.USER):${GITHUB_TOKEN}@github.com/$(params.USER)/$(params.REPO) --branch=$(params.BRANCH)
      cd iter8-gitops/deploy
      rm -f iter8.yaml
      rm -f experiment.yaml
      sed 's/-candidate/-stable/g' deployment-candidate.yaml > deployment.yaml
      rm -f deployment-candidate.yaml

      git add -A
      git commit -a -m 'Promote candidate version'
      git push -f origin $(params.BRANCH)
    env:
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: $(params.GITHUB-TOKEN-SECRET)
          key: token
