apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: start-experiment
  annotations:
    tekton.dev/displayName: "Start an Iter8 experiment"
spec:
  description: >-
    This task create a candidate and Iter8 experiment resource in
    the Env repo and make a PR from the changes

  params:
    - name: VERSION
      description: version of the candidate deployment
    - name: USER
      description: Github username
    - name: REPO
      description: Github repo name
    - name: BRANCH
      description: Base branch PR is opened against
    - name: GITHUB-TOKEN-SECRET
      description: Holds Github token

  steps:
  - name: start-experiment
    image: iter8/iter8:latest
    script: |
      #!/usr/bin/env sh
      git config --global user.email 'iter8@iter8.tools'
      git config --global user.name 'Iter8'
      git clone https://$(params.USER):${GITHUB_TOKEN}@github.com/$(params.USER)/$(params.REPO) --branch=$(params.BRANCH)
      cd iter8-gitops
      CANDIDATE_SVC=`kubectl get services | grep iter8-app-candidate | awk '{print $3}'`:8000
      GATEWAY_SVC=`kubectl get route el-iter8-eventlistener --template='http://{{.spec.host}}'`
      sed "s#CANDIDATE_SVC#$CANDIDATE_SVC#g; s#GATEWAY_SVC#$GATEWAY_SVC#g" experiment.tpl > experiment.yaml
      echo "=========== experiment.yaml ===========";
      cat experiment.yaml
      iter8 gen k8s > deploy.yaml
      echo "=========== deploy.yaml ==============="; echo ""
      cat deploy.yaml
      # take advantage of /workspace shared directory between steps of the same task
      cp deploy.yaml /workspace
    env:
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: $(params.GITHUB-TOKEN-SECRET)
          key: token
        
  - name: git-commit
    image: alpine/git:latest
    script: |
      #!/usr/bin/env sh
      apk add make
      #git config --global user.email 'iter8@iter8.tools'
      #git config --global user.name 'Iter8'
      #git clone https://$(params.USER):${GITHUB_TOKEN}@github.com/$(params.USER)/$(params.REPO) --branch=$(params.BRANCH)
      cd iter8-gitops
      (cd templates; VERSION=$(params.VERSION) make)
      (cd deploy; cp /workspace/deploy.yaml .)
      git add -A
      git commit -a -m 'start Iter8 experiment'
      git push -f origin $(params.BRANCH)
    env:
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: $(params.GITHUB-TOKEN-SECRET)
          key: token
        
