apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: start-experiment
  annotations:
    tekton.dev/displayName: "Start an Iter8 experiment"
spec:
  description: >-
    This task create a candidate and Iter8 experiment resource in
    the Env repo and make a PR from the changes

  params:
    - name: VERSION
      description: version of the candidate deployment
    - name: USER
      description: Github username
    - name: REPO
      description: Github repo name
    - name: BRANCH
      description: Base branch PR is opened against
    - name: GITHUB-TOKEN-SECRET
      description: Holds Github token

  steps:
  - name: start-experiment
    image: iter8/iter8:latest
    script: |
      #!/usr/bin/env sh
      echo "this is the start-experiment task"
  - name: git-commit
    image: alpine/git:latest
    script: |
      #!/usr/bin/env sh
      git config --global user.email 'iter8@iter8.tools'
      git config --global user.name 'Iter8'
      git clone https://$(params.USER):${GITHUB_TOKEN}@github.com/$(params.USER)/$(params.REPO) --branch=$(params.BRANCH)
      cd iter8-gitops
      echo "hello" > test
      git add -A
      git commit -a -m 'start Iter8 experiment'
      git push -f origin $(params.BRANCH)
    env:
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: $(params.GITHUB-TOKEN-SECRET)
          key: token
        
