apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: iter8-git
spec:
  type: git
  params:
    - name: url
      value: https://github.com/huang195/iter8-gitops.git
    - name: revision
      value: main
    - name: refspec
      value: refs/heads/main:refs/heads/main
    - name: depth
      value: "0"
