# task 1: generate HTTP requests for the model
# collect Iter8's built-in latency and error related metrics
- task: gen-load-and-collect-metrics-http
  with:
    percentiles:
    - 95
    versionInfo:
    - url: 172.21.154.181:8000

# task 2: validate service level objectives 
# using the metrics collected in the above task
- task: assess-app-versions
  with:
    SLOs:
      # error rate must be 0
    - metric: built-in/http-error-rate
      upperLimit: 0
      # 95th percentile latency must be under 100 msec
    - metric: built-in/http-latency-p95
      upperLimit: 150

# task 3: if SLOs are satisfied, do something
- if: SLOs()
  run: |
    echo "Promote"
    curl -v -H 'Content-Type: application/json' \
        -d '{ "action": "promote", "pull_request": { "merged": "", "commits": "", "base": { "ref": "" }}}' \
        http://el-iter8-eventlistener-default.openshift-f0f5a1e5d9c5f09a7767f1f253010cba-0000.us-east.containers.appdomain.cloud

# task 4: if SLOs are not satisfied, do something else
- if: not SLOs()
  run: |
    echo "Call cleanup"
    curl -v -H 'Content-Type: application/json' \
        -d '{ "action": "cleanup", "pull_request": { "merged": "", "commits": "", "base": { "ref": "" }}}' \
        http://el-iter8-eventlistener-default.openshift-f0f5a1e5d9c5f09a7767f1f253010cba-0000.us-east.containers.appdomain.cloud
